#!/bin/bash

cd /home/ubuntu/mbucio/tools/openROAD/flow


make DESIGN_CONFIG=./designs/gf180/riscv_v_execute/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_execute/base/ ../../../models/riscv_v/reports/gf180/riscv_v_execute; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_execute; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_execute/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_arithmetic_ALU/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_arithmetic_ALU/base/ ../../../models/riscv_v/reports/gf180/riscv_v_arithmetic_ALU; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_arithmetic_ALU; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_arithmetic_ALU/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_adder/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_adder/base/ ../../../models/riscv_v/reports/gf180/riscv_v_adder; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_adder; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_adder/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_mul/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_mul/base/ ../../../models/riscv_v/reports/gf180/riscv_v_mul; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_mul; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_mul/config.mk;

make DESIGN_CONFIG=./designs/sky130hd/riscv_v_execute/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_execute/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_execute; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_execute; make clean_all DESIGN_CONFIG=./designs/sky130hd/riscv_v_execute/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_arithmetic_ALU/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_arithmetic_ALU/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_arithmetic_ALU; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_arithmetic_ALU; make clean_all DESIGN_CONFIG=./designs/sky130hd/riscv_v_arithmetic_ALU/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_adder/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_adder/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_adder; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_adder; make clean_all DESIGN_CONFIG=./designs/sky130hd/riscv_v_adder/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_mul/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_mul/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_mul; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_mul; make clean_all DESIGN_CONFIG=./designs/sky130hd/riscv_v_mul/config.mk;

make DESIGN_CONFIG=./designs/nangate45/riscv_v_rf/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_rf/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_rf; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_rf; make clean_all DESIGN_CONFIG=./designs/nangate45/riscv_v_rf/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_execute/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_execute/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_execute; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_execute; make clean_all DESIGN_CONFIG=./designs/nangate45/riscv_v_execute/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_arithmetic_ALU/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_arithmetic_ALU/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_arithmetic_ALU; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_arithmetic_ALU; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_arithmetic_ALU/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_adder/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_adder/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_adder; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_adder; make clean_all DESIGN_CONFIG=./designs/nangate45/riscv_v_adder/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_mul/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_mul/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_mul; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_mul; make clean_all DESIGN_CONFIG=./designs/nangate45/riscv_v_mul/config.mk;
