#!/bin/bash

cd /home/ubuntu/mbucio/tools/openROAD/flow

make DESIGN_CONFIG=./designs/gf180/riscv_v_csr_ctrl/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_csr_ctrl/base/ ../../../models/riscv_v/reports/gf180/riscv_v_csr_ctrl; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_csr_ctrl; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_csr_ctrl/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_csr/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_csr/base/ ../../../models/riscv_v/reports/gf180/riscv_v_csr; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_csr; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_csr/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_rf_ctrl/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_rf_ctrl/base/ ../../../models/riscv_v/reports/gf180/riscv_v_rf_ctrl; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_rf_ctrl; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_rf_ctrl/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_rf/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_rf/base/ ../../../models/riscv_v/reports/gf180/riscv_v_rf; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_rf; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_rf/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_execute/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_execute/base/ ../../../models/riscv_v/reports/gf180/riscv_v_execute; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_execute; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_execute/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_decode_element/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_decode_element/base/ ../../../models/riscv_v/reports/gf180/riscv_v_decode_element; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_decode_element; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_decode_element/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_bypass/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_bypass/base/ ../../../models/riscv_v/reports/gf180/riscv_v_bypass; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_bypass; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bypass/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_reduct_src/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_reduct_src/base/ ../../../models/riscv_v/reports/gf180/riscv_v_reduct_src; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_reduct_src; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_reduct_src/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_swizzle/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_swizzle/base/ ../../../models/riscv_v/reports/gf180/riscv_v_swizzle; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_swizzle; make clean_all  DESIGN_CONFIG=./designs/gf180/riscv_v_swizzle/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_logic_ALU/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_logic_ALU/base/ ../../../models/riscv_v/reports/gf180/riscv_v_logic_ALU; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_logic_ALU; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_logic_ALU/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_bw_and/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_bw_and/base/ ../../../models/riscv_v/reports/gf180/riscv_v_bw_and; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_bw_and; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bw_and/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_bw_or/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_bw_or/base/ ../../../models/riscv_v/reports/gf180/riscv_v_bw_or; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_bw_or; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bw_or/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_bw_xor/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_bw_xor/base/ ../../../models/riscv_v/reports/gf180/riscv_v_bw_xor; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_bw_xor; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bw_xor/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_shifter/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_shifter/base/ ../../../models/riscv_v/reports/gf180/riscv_v_shifter; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_shifter; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_shifter/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_arithmetic_ALU/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_arithmetic_ALU/base/ ../../../models/riscv_v/reports/gf180/riscv_v_arithmetic_ALU; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_arithmetic_ALU; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_arithmetic_ALU/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_adder/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_adder/base/ ../../../models/riscv_v/reports/gf180/riscv_v_adder; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_adder; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_adder/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_mul/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_mul/base/ ../../../models/riscv_v/reports/gf180/riscv_v_mul; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_mul; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_mul/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_extend/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_extend/base/ ../../../models/riscv_v/reports/gf180/riscv_v_extend; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_extend; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_extend/config.mk;
make DESIGN_CONFIG=./designs/gf180/riscv_v_permutation_ALU/config.mk | tee log.txt; cp -r reports/gf180/riscv_v_permutation_ALU/base/ ../../../models/riscv_v/reports/gf180/riscv_v_permutation_ALU; cp log.txt ../../../models/riscv_v/reports/gf180/riscv_v_permutation_ALU; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_permutation_ALU/config.mk;


make DESIGN_CONFIG=./designs/sky130hd/riscv_v_csr_ctrl/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_csr_ctrl/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_csr_ctrl; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_csr_ctrl; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_csr_ctrl/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_csr/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_csr/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_csr; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_csr; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_csr/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_rf_ctrl/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_rf_ctrl/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_rf_ctrl; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_rf_ctrl; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_rf_ctrl/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_rf/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_rf/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_rf; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_rf; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_rf/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_execute/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_execute/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_execute; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_execute; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_execute/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_decode_element/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_decode_element/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_decode_element; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_decode_element; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_decode_element/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_bypass/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_bypass/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_bypass; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_bypass; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bypass/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_reduct_src/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_reduct_src/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_reduct_src; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_reduct_src; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_reduct_src/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_swizzle/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_swizzle/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_swizzle; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_swizzle; make clean_all  DESIGN_CONFIG=./designs/gf180/riscv_v_swizzle/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_logic_ALU/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_logic_ALU/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_logic_ALU; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_logic_ALU; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_logic_ALU/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_bw_and/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_bw_and/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_bw_and; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_bw_and; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bw_and/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_bw_or/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_bw_or/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_bw_or; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_bw_or; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bw_or/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_bw_xor/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_bw_xor/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_bw_xor; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_bw_xor; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bw_xor/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_shifter/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_shifter/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_shifter; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_shifter; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_shifter/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_arithmetic_ALU/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_arithmetic_ALU/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_arithmetic_ALU; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_arithmetic_ALU; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_arithmetic_ALU/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_adder/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_adder/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_adder; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_adder; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_adder/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_mul/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_mul/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_mul; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_mul; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_mul/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_extend/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_extend/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_extend; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_extend; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_extend/config.mk;
make DESIGN_CONFIG=./designs/sky130hd/riscv_v_permutation_ALU/config.mk | tee log.txt; cp -r reports/sky130hd/riscv_v_permutation_ALU/base/ ../../../models/riscv_v/reports/sky130hd/riscv_v_permutation_ALU; cp log.txt ../../../models/riscv_v/reports/sky130hd/riscv_v_permutation_ALU; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_permutation_ALU/config.mk;

make DESIGN_CONFIG=./designs/nangate45/riscv_v_csr_ctrl/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_csr_ctrl/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_csr_ctrl; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_csr_ctrl; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_csr_ctrl/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_csr/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_csr/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_csr; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_csr; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_csr/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_rf_ctrl/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_rf_ctrl/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_rf_ctrl; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_rf_ctrl; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_rf_ctrl/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_rf/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_rf/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_rf; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_rf; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_rf/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_execute/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_execute/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_execute; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_execute; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_execute/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_decode_element/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_decode_element/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_decode_element; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_decode_element; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_decode_element/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_bypass/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_bypass/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_bypass; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_bypass; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bypass/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_reduct_src/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_reduct_src/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_reduct_src; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_reduct_src; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_reduct_src/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_swizzle/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_swizzle/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_swizzle; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_swizzle; make clean_all  DESIGN_CONFIG=./designs/gf180/riscv_v_swizzle/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_logic_ALU/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_logic_ALU/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_logic_ALU; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_logic_ALU; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_logic_ALU/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_bw_and/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_bw_and/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_bw_and; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_bw_and; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bw_and/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_bw_or/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_bw_or/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_bw_or; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_bw_or; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bw_or/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_bw_xor/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_bw_xor/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_bw_xor; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_bw_xor; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bw_xor/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_shifter/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_shifter/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_shifter; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_shifter; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_shifter/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_arithmetic_ALU/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_arithmetic_ALU/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_arithmetic_ALU; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_arithmetic_ALU; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_arithmetic_ALU/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_adder/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_adder/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_adder; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_adder; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_adder/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_mul/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_mul/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_mul; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_mul; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_mul/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_extend/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_extend/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_extend; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_extend; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_extend/config.mk;
make DESIGN_CONFIG=./designs/nangate45/riscv_v_permutation_ALU/config.mk | tee log.txt; cp -r reports/nangate45/riscv_v_permutation_ALU/base/ ../../../models/riscv_v/reports/nangate45/riscv_v_permutation_ALU; cp log.txt ../../../models/riscv_v/reports/nangate45/riscv_v_permutation_ALU; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_permutation_ALU/config.mk;

make DESIGN_CONFIG=./designs/asap7/riscv_v_csr_ctrl/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_csr_ctrl/base/ ../../../models/riscv_v/reports/asap7/riscv_v_csr_ctrl; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_csr_ctrl; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_csr_ctrl/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_csr/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_csr/base/ ../../../models/riscv_v/reports/asap7/riscv_v_csr; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_csr; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_csr/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_rf_ctrl/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_rf_ctrl/base/ ../../../models/riscv_v/reports/asap7/riscv_v_rf_ctrl; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_rf_ctrl; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_rf_ctrl/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_rf/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_rf/base/ ../../../models/riscv_v/reports/asap7/riscv_v_rf; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_rf; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_rf/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_execute/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_execute/base/ ../../../models/riscv_v/reports/asap7/riscv_v_execute; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_execute; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_execute/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_decode_element/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_decode_element/base/ ../../../models/riscv_v/reports/asap7/riscv_v_decode_element; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_decode_element; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_decode_element/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_bypass/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_bypass/base/ ../../../models/riscv_v/reports/asap7/riscv_v_bypass; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_bypass; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bypass/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_reduct_src/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_reduct_src/base/ ../../../models/riscv_v/reports/asap7/riscv_v_reduct_src; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_reduct_src; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_reduct_src/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_swizzle/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_swizzle/base/ ../../../models/riscv_v/reports/asap7/riscv_v_swizzle; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_swizzle; make clean_all  DESIGN_CONFIG=./designs/gf180/riscv_v_swizzle/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_logic_ALU/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_logic_ALU/base/ ../../../models/riscv_v/reports/asap7/riscv_v_logic_ALU; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_logic_ALU; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_logic_ALU/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_bw_and/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_bw_and/base/ ../../../models/riscv_v/reports/asap7/riscv_v_bw_and; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_bw_and; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bw_and/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_bw_or/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_bw_or/base/ ../../../models/riscv_v/reports/asap7/riscv_v_bw_or; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_bw_or; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bw_or/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_bw_xor/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_bw_xor/base/ ../../../models/riscv_v/reports/asap7/riscv_v_bw_xor; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_bw_xor; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_bw_xor/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_shifter/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_shifter/base/ ../../../models/riscv_v/reports/asap7/riscv_v_shifter; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_shifter; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_shifter/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_arithmetic_ALU/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_arithmetic_ALU/base/ ../../../models/riscv_v/reports/asap7/riscv_v_arithmetic_ALU; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_arithmetic_ALU; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_arithmetic_ALU/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_adder/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_adder/base/ ../../../models/riscv_v/reports/asap7/riscv_v_adder; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_adder; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_adder/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_mul/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_mul/base/ ../../../models/riscv_v/reports/asap7/riscv_v_mul; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_mul; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_mul/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_extend/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_extend/base/ ../../../models/riscv_v/reports/asap7/riscv_v_extend; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_extend; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_extend/config.mk;
make DESIGN_CONFIG=./designs/asap7/riscv_v_permutation_ALU/config.mk | tee log.txt; cp -r reports/asap7/riscv_v_permutation_ALU/base/ ../../../models/riscv_v/reports/asap7/riscv_v_permutation_ALU; cp log.txt ../../../models/riscv_v/reports/asap7/riscv_v_permutation_ALU; make clean_all DESIGN_CONFIG=./designs/gf180/riscv_v_permutation_ALU/config.mk;