###############################################################
#  Generated by:      Cadence Innovus 21.12-s106_1
#  OS:                Linux x86_64(Host ID ip-172-31-46-123.us-east-2.compute.internal)
#  Generated on:      Mon Dec  5 08:33:27 2022
#  Design:            RISC_V_pipeline
#  Command:           create_ccopt_clock_tree_spec -file riscv_pipe_ccopt_CTS.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk_pad true

# Clocks present at pin clk_pad
#   clk_pad (period 9.200ns) in timing_config Constraint_Mode_WC([../synthesis_genus/outputs/RISC_V_pipeline_opt.CM_riscv_pipe_slow.sdc])
#   clk_pad (period 9.200ns) in timing_config Constraint_Mode_BC([../synthesis_genus/outputs/RISC_V_pipeline_opt.CM_riscv_pipe_fast.sdc])
create_ccopt_clock_tree -name clk_pad -source clk_pad -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner Delay_Corner_WC -early -clock_tree clk_pad 0.030
set_ccopt_property target_max_trans_sdc -delay_corner Delay_Corner_WC -late -clock_tree clk_pad 0.050
# Clock tree offset inferred from set_clock_latency -source assertions:
set_ccopt_property source_latency -delay_corner Delay_Corner_WC -early -rise -clock_tree clk_pad 0.020
set_ccopt_property source_latency -delay_corner Delay_Corner_WC -early -fall -clock_tree clk_pad 0.030
set_ccopt_property source_latency -delay_corner Delay_Corner_WC -late -rise -clock_tree clk_pad 0.020
set_ccopt_property source_latency -delay_corner Delay_Corner_WC -late -fall -clock_tree clk_pad 0.030
set_ccopt_property source_latency -delay_corner Delay_Corner_BC -early -rise -clock_tree clk_pad 0.020
set_ccopt_property source_latency -delay_corner Delay_Corner_BC -early -fall -clock_tree clk_pad 0.030
set_ccopt_property source_latency -delay_corner Delay_Corner_BC -late -rise -clock_tree clk_pad 0.020
set_ccopt_property source_latency -delay_corner Delay_Corner_BC -late -fall -clock_tree clk_pad 0.030
# Clock period setting for source pin of clk_pad
set_ccopt_property clock_period -pin clk_pad 9.2

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk_pad in timing_config:Constraint_Mode_WC (sdc ../synthesis_genus/outputs/RISC_V_pipeline_opt.CM_riscv_pipe_slow.sdc)
create_ccopt_skew_group -name clk_pad/Constraint_Mode_WC -sources clk_pad -auto_sinks
set_ccopt_property include_source_latency -skew_group clk_pad/Constraint_Mode_WC true
set_ccopt_property target_insertion_delay -skew_group clk_pad/Constraint_Mode_WC 0.030
set_ccopt_property extracted_from_clock_name -skew_group clk_pad/Constraint_Mode_WC clk_pad
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk_pad/Constraint_Mode_WC Constraint_Mode_WC
set_ccopt_property extracted_from_delay_corners -skew_group clk_pad/Constraint_Mode_WC Delay_Corner_WC

# Skew group to balance non generated clock:clk_pad in timing_config:Constraint_Mode_BC (sdc ../synthesis_genus/outputs/RISC_V_pipeline_opt.CM_riscv_pipe_fast.sdc)
create_ccopt_skew_group -name clk_pad/Constraint_Mode_BC -sources clk_pad -auto_sinks
set_ccopt_property include_source_latency -skew_group clk_pad/Constraint_Mode_BC true
set_ccopt_property extracted_from_clock_name -skew_group clk_pad/Constraint_Mode_BC clk_pad
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk_pad/Constraint_Mode_BC Constraint_Mode_BC
set_ccopt_property extracted_from_delay_corners -skew_group clk_pad/Constraint_Mode_BC Delay_Corner_BC


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

